"""Panchanga validation fixtures derived from JHora (primary oracle) and AstroSage (secondary).

Strategy: 8 fixtures covering 4 reference charts x 2 epochs (birth-moment and
2026-06-16 12:30 local). P1.2a only exercises the 2026-06-16 fixtures for
sunrise/sunset testing; birth-moment fixtures are defined here but unused until
P1.2b asserts full Panchanga element values.

Coordinate sources: JHora birth-data entry for each chart. Sunrise/sunset and
all Panchanga element expected values generated by JHora at each moment.

Hardest case: Sheridan_20260616_1230_SAST — Ardra nakshatra at 0.85% left
(nakshatra boundary), SAST timezone, Southern Hemisphere.

P1.2c fields (choghadiya, kalam windows, abhijit):
  Source: Muhurtha-Chinthamani (Abhijit) + Drik Panchang tables (others).
  PVR's book does not cover these topics.
  Expected values are implementation-derived (not independently JHora-validated).
  All 4 fixtures are Tuesday 2026-06-16: chog_day_first=Rog, chog_night_first=Kaal.
  Rahu Kalam start times stored here for regression testing.
"""

from datetime import datetime, timedelta, timezone

IST = timezone(timedelta(hours=5, minutes=30))
SAST = timezone(timedelta(hours=2))
BST = timezone(timedelta(hours=1))

FIXTURES = [
    {
        "name": "Sulabh_20260616_1230_IST",
        "moment": datetime(2026, 6, 16, 12, 30, 0, tzinfo=IST),
        "latitude": 22 + 34 / 60,       # 22°34'N (Calcutta — JHora)
        "longitude": 88 + 22 / 60,      # 88°22'E
        "expected_sunrise_hms": (4, 55, 52),
        "expected_sunset_hms": (18, 18, 38),
        "expected_tithi_name": "Sukla Dwitiya",
        "expected_tithi_percent_left": 60.66,
        "expected_nakshatra_name": "Ardra",
        "expected_nakshatra_pada": None,   # JHora doesn't print pada in Key Info
        "expected_nakshatra_percent_left": 17.37,
        "expected_yoga_name": "Vriddhi",
        "expected_yoga_percent_left": 60.16,
        "expected_karana_name": "Balava",
        "expected_karana_percent_left": 21.31,
        "expected_vara_name": "Tuesday",
        "expected_hora_lord": "Mars",
        "expected_ayanamsa_dms": (24, 12, 38.22),
        "expected_chog_day_first": "Rog",
        "expected_chog_night_first": "Kaal",
        "expected_rahu_kalam_start_hms": (14, 57, 54),  # implementation-derived
    },
    {
        "name": "Surbhi_20260616_1230_IST",
        "moment": datetime(2026, 6, 16, 12, 30, 0, tzinfo=IST),
        "latitude": 27 + 50 / 60,       # 27°50'N (Patna)
        "longitude": 81 + 46 / 60,      # 81°46'E
        "expected_sunrise_hms": (5, 10, 54),
        "expected_sunset_hms": (18, 56, 24),
        "expected_tithi_name": "Sukla Dwitiya",
        "expected_tithi_percent_left": 60.66,
        "expected_nakshatra_name": "Ardra",
        "expected_nakshatra_pada": None,
        "expected_nakshatra_percent_left": 17.37,
        "expected_yoga_name": "Vriddhi",
        "expected_yoga_percent_left": 60.16,
        "expected_karana_name": "Balava",
        "expected_karana_percent_left": 21.31,
        "expected_vara_name": "Tuesday",
        "expected_hora_lord": "Mars",
        "expected_ayanamsa_dms": (24, 12, 38.22),
        "expected_chog_day_first": "Rog",
        "expected_chog_night_first": "Kaal",
        "expected_rahu_kalam_start_hms": (15, 30, 0),   # implementation-derived
    },
    {
        "name": "Sheridan_20260616_1230_SAST",
        "moment": datetime(2026, 6, 16, 12, 30, 0, tzinfo=SAST),
        "latitude": -(29 + 51 / 60),    # 29°51'S (Durban)
        "longitude": 31 + 1 / 60,       # 31°01'E
        "expected_sunrise_hms": (6, 54, 0),
        "expected_sunset_hms": (16, 59, 17),
        "expected_tithi_name": "Sukla Dwitiya",
        "expected_tithi_percent_left": 43.45,
        "expected_nakshatra_name": "Ardra",
        "expected_nakshatra_pada": None,
        "expected_nakshatra_percent_left": 0.85,
        "expected_yoga_name": "Vriddhi",
        "expected_yoga_percent_left": 42.59,
        "expected_karana_name": "Kaulava",
        "expected_karana_percent_left": 86.91,
        "expected_vara_name": "Tuesday",
        "expected_hora_lord": "Saturn",
        "expected_ayanamsa_dms": (24, 12, 38.24),
        "notes": "Hardest case — Nakshatra boundary at 0.85% left of Ardra",
        "expected_chog_day_first": "Rog",
        "expected_chog_night_first": "Kaal",
        "expected_rahu_kalam_start_hms": (14, 27, 56),  # implementation-derived; 75.66 min seg (shortest day)
    },
    {
        "name": "David_20260616_1230_BST",
        "moment": datetime(2026, 6, 16, 12, 30, 0, tzinfo=BST),
        "latitude": 51 + 30 / 60,       # 51°30'N (London)
        "longitude": -(0 + 7 / 60),     # 0°07'W
        "expected_sunrise_hms": (4, 49, 43),
        "expected_sunset_hms": (21, 12, 52),
        "expected_tithi_name": "Sukla Dwitiya",
        "expected_tithi_percent_left": 38.55,
        "expected_nakshatra_name": "Punarvasu",
        "expected_nakshatra_pada": None,
        "expected_nakshatra_percent_left": 96.13,
        "expected_yoga_name": "Vriddhi",
        "expected_yoga_percent_left": 37.57,
        "expected_karana_name": "Kaulava",
        "expected_karana_percent_left": 77.09,
        "expected_vara_name": "Tuesday",
        "expected_hora_lord": "Mars",
        "expected_ayanamsa_dms": (24, 12, 38.25),
        "notes": "DST handling — London BST is GMT+1",
        "expected_chog_day_first": "Rog",
        "expected_chog_night_first": "Kaal",
        "expected_rahu_kalam_start_hms": (17, 7, 3),    # implementation-derived; 122.89 min seg (longest day)
    },
]
